package assertions

// Assertion 数据断言检查类型
type Assertion string

const (
	//ShouldEqual 应该相等
	ShouldEqual                  Assertion = "shouldEqual"
	ShouldNotEqual               Assertion = "shouldNotEqual"
	ShouldResemble               Assertion = "shouldResemble"
	ShouldNotResemble            Assertion = "shouldNotResemble"
	ShouldPointTo                Assertion = "shouldPointTo"
	ShouldNotPointTo             Assertion = "shouldNotPointTo"
	ShouldBeNil                  Assertion = "shouldBeNil"
	ShouldNotBeNil               Assertion = "shouldNotBeNil"
	ShouldBeTrue                 Assertion = "shouldBeTrue"
	ShouldBeFalse                Assertion = "shouldBeFalse"
	ShouldBeZeroValue            Assertion = "shouldBeZeroValue"
	ShouldBeGreaterThan          Assertion = "shouldBeGreaterThan"
	ShouldBeGreaterThanOrEqualTo Assertion = "shouldBeGreaterThanOrEqualTo"
	ShouldBeLessThan             Assertion = "shouldBeLessThan"
	ShouldBeLessThanOrEqualTo    Assertion = "shouldBeLessThanOrEqualTo"
	ShouldBeBetween              Assertion = "shouldBeBetween"
	ShouldNotBeBetween           Assertion = "shouldNotBeBetween"
	ShouldBeBetweenOrEqual       Assertion = "shouldBeBetweenOrEqual"
	ShouldNotBeBetweenOrEqual    Assertion = "shouldNotBeBetweenOrEqual"
	ShouldAlmostEqual            Assertion = "shouldAlmostEqual"
	ShouldNotAlmostEqual         Assertion = "shouldNotAlmostEqual"
	ShouldContain                Assertion = "shouldContain"
	ShouldNotContain             Assertion = "shouldNotContain"
	ShouldBeIn                   Assertion = "shouldBeIn"
	ShouldNotBeIn                Assertion = "shouldNotBeIn"
	ShouldBeEmpty                Assertion = "shouldBeEmpty"
	ShouldNotBeEmpty             Assertion = "shouldNotBeEmpty"
	ShouldContainKey             Assertion = "shouldContainKey"
	ShouldNotContainKey          Assertion = "shouldNotContainKey"
	ShouldStartWith              Assertion = "shouldStartWith"
	ShouldNotStartWith           Assertion = "shouldNotStartWith"
	ShouldEndWith                Assertion = "shouldEndWith"
	ShouldNotEndWith             Assertion = "shouldNotEndWith"
	ShouldContainSubstring       Assertion = "shouldContainSubstring"
	ShouldNotContainSubstring    Assertion = "shouldNotContainSubstring"
	ShouldBeBlank                Assertion = "shouldBeBlank"
	ShouldNotBeBlank             Assertion = "shouldNotBeBlank"
	ShouldHappenBefore           Assertion = "shouldHappenBefore"
	ShouldHappenOnOrBefore       Assertion = "shouldHappenOnOrBefore"
	ShouldHappenAfter            Assertion = "shouldHappenAfter"
	ShouldHappenOnOrAfter        Assertion = "shouldHappenOnOrAfter"
	ShouldHappenBetween          Assertion = "shouldHappenBetween"
	ShouldHappenOnOrBetween      Assertion = "shouldHappenOnOrBetween"
	ShouldNotHappenOnOrBetween   Assertion = "shouldNotHappenOnOrBetween"
	ShouldHappenWithin           Assertion = "shouldHappenWithin"
	ShouldNotHappenWith          Assertion = "shouldNotHappenWithinin"
)
